#include <iostream>
#include "..\ANSIcolor.hpp"

int main(int argc, char* argv[]){

    if(argv[2] == "--help" || argv[2] == "/?"){
        std::cout << "256-bit ANSI-Color-Palette" << std::endl;
        std::cout << "Usage: 'ansicolor [<option>]'" << std::endl;
        std::cout << "Options: -op1, op2, op3" << std::endl;
        std::cout << "Copyright (C) 2024 - Jason Weber. All rights reserved." << std::endl;
    }
    
    if(argv[2] == NULL){
    std::cout << ANSI_COLOR_0 << " 0 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_1 << " 1 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_2 << " 2 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_3 << " 3 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_4 << " 4 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_5 << " 5 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_6 << " 6 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_7 << " 7 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_8 << " 8 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_9 << " 9 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_10 << " 10 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_11 << " 11 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_12 << " 12 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_13 << " 13 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_14 << " 14 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_15 << " 15 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_16 << " 16 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_17 << " 17 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_18 << " 18 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_19 << " 19 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_20 << " 20 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_21 << " 21 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_22 << " 22 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_23 << " 23 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_24 << " 24 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_25 << " 25 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_26 << " 26 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_27 << " 27 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_28 << " 28 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_29 << " 29 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_30 << " 30 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_31 << " 31 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_32 << " 32 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_33 << " 33 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_34 << " 34 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_35 << " 35 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_36 << " 36 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_37 << " 37 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_38 << " 38 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_39 << " 39 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_40 << " 40 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_41 << " 41 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_42 << " 42 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_43 << " 43 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_44 << " 44 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_45 << " 45 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_46 << " 46 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_47 << " 47 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_48 << " 48 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_49 << " 49 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_50 << " 50 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_51 << " 51 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_52 << " 52 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_53 << " 53 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_54 << " 54 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_55 << " 55 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_56 << " 56 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_57 << " 57 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_58 << " 58 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_59 << " 59 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_60 << " 60 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_61 << " 61 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_62 << " 62 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_63 << " 63 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_64 << " 64 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_65 << " 65 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_66 << " 66 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_67 << " 67 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_68 << " 68 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_69 << " 69 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_70 << " 70 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_71 << " 71 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_72 << " 72 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_73 << " 73 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_74 << " 74 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_75 << " 75 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_76 << " 76 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_77 << " 77 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_78 << " 78 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_79 << " 79 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_80 << " 80 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_81 << " 81 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_82 << " 82 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_83 << " 83 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_84 << " 84 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_85 << " 85 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_86 << " 86 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_87 << " 87 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_88 << " 88 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_89 << " 89 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_90 << " 90 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_91 << " 91 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_92 << " 92 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_93 << " 93 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_94 << " 94 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_95 << " 95 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_96 << " 96 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_97 << " 97 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_98 << " 98 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_99 << " 99 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_100 << " 100 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_101 << " 101 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_102 << " 102 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_103 << " 103 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_104 << " 104 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_105 << " 105 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_106 << " 106 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_107 << " 107 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_108 << " 108 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_109 << " 109 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_110 << " 110 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_111 << " 111 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_112 << " 112 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_113 << " 113 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_114 << " 114 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_115 << " 115 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_116 << " 116 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_117 << " 117 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_118 << " 118 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_119 << " 119 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_120 << " 120 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_121 << " 121 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_122 << " 122 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_123 << " 123 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_124 << " 124 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_125 << " 125 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_126 << " 126 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_127 << " 127 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_128 << " 128 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_129 << " 129 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_130 << " 130 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_131 << " 131 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_132 << " 132 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_133 << " 133 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_134 << " 134 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_135 << " 135 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_136 << " 136 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_137 << " 137 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_138 << " 138 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_139 << " 139 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_140 << " 140 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_141 << " 141 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_142 << " 142 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_143 << " 143 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_144 << " 144 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_145 << " 145 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_146 << " 146 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_147 << " 147 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_148 << " 148 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_149 << " 149 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_150 << " 150 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_151 << " 151 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_152 << " 152 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_153 << " 153 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_154 << " 154 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_155 << " 155 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_156 << " 156 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_157 << " 157 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_158 << " 158 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_159 << " 159 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_160 << " 160 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_161 << " 161 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_162 << " 162 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_163 << " 163 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_164 << " 164 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_165 << " 165 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_166 << " 166 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_167 << " 167 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_168 << " 168 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_169 << " 169 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_170 << " 170 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_171 << " 171 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_172 << " 172 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_173 << " 173 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_174 << " 174 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_175 << " 175 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_176 << " 176 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_177 << " 177 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_178 << " 178 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_179 << " 179 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_180 << " 180 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_181 << " 181 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_182 << " 182 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_183 << " 183 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_184 << " 184 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_185 << " 185 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_186 << " 186 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_187 << " 187 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_188 << " 188 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_189 << " 189 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_190 << " 190 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_191 << " 191 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_192 << " 192 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_193 << " 193 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_194 << " 194 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_195 << " 195 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_196 << " 196 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_197 << " 197 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_198 << " 198 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_199 << " 199 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_200 << " 200 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_201 << " 201 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_202 << " 202 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_203 << " 203 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_204 << " 204 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_205 << " 205 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_206 << " 206 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_207 << " 207 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_208 << " 208 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_209 << " 209 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_210 << " 210 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_211 << " 211 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_212 << " 212 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_213 << " 213 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_214 << " 214 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_215 << " 215 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_216 << " 216 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_217 << " 217 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_218 << " 218 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_219 << " 219 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_220 << " 220 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_221 << " 221 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_222 << " 222 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_223 << " 223 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_224 << " 224 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_225 << " 225 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_226 << " 226 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_227 << " 227 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_228 << " 228 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_229 << " 229 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_230 << " 230 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_231 << " 231 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_232 << " 232 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_233 << " 233 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_234 << " 234 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_235 << " 235 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_236 << " 236 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_237 << " 237 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_238 << " 238 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_239 << " 239 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_240 << " 240 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_241 << " 241 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_242 << " 242 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_243 << " 243 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_244 << " 244 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_245 << " 245 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_246 << " 246 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_247 << " 247 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_248 << " 248 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_249 << " 249 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_250 << " 250 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_251 << " 251 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_252 << " 252 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_253 << " 253 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_254 << " 254 " << ANSI_COLOR_RESET;
    std::cout << ANSI_COLOR_255 << " 255 " << ANSI_COLOR_RESET;
    }

    else if(argv[2] == "--op1" || argv[2] == "-op1"){

        std::cout << ANSI_COLOR_0 << "Color: 0 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_1 << "Color: 1 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_2 << "Color: 2 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_3 << "Color: 3 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_4 << "Color: 4 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_5 << "Color: 5 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_6 << "Color: 6 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_7 << "Color: 7 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_8 << "Color: 8 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_9 << "Color: 9 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_10 << "Color: 10 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_11 << "Color: 11 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_12 << "Color: 12 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_13 << "Color: 13 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_14 << "Color: 14 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_15 << "Color: 15 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_16 << "Color: 16 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_17 << "Color: 17 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_18 << "Color: 18 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_19 << "Color: 19 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_20 << "Color: 20 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_21 << "Color: 21 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_22 << "Color: 22 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_23 << "Color: 23 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_24 << "Color: 24 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_25 << "Color: 25 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_26 << "Color: 26 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_27 << "Color: 27 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_28 << "Color: 28 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_29 << "Color: 29 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_30 << "Color: 30 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_31 << "Color: 31 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_32 << "Color: 32 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_33 << "Color: 33 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_34 << "Color: 34 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_35 << "Color: 35 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_36 << "Color: 36 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_37 << "Color: 37 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_38 << "Color: 38 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_39 << "Color: 39 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_40 << "Color: 40 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_41 << "Color: 41 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_42 << "Color: 42 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_43 << "Color: 43 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_44 << "Color: 44 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_45 << "Color: 45 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_46 << "Color: 46 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_47 << "Color: 47 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_48 << "Color: 48 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_49 << "Color: 49 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_50 << "Color: 50 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_51 << "Color: 51 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_52 << "Color: 52 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_53 << "Color: 53 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_54 << "Color: 54 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_55 << "Color: 55 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_56 << "Color: 56 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_57 << "Color: 57 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_58 << "Color: 58 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_59 << "Color: 59 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_60 << "Color: 60 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_61 << "Color: 61 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_62 << "Color: 62 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_63 << "Color: 63 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_64 << "Color: 64 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_65 << "Color: 65 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_66 << "Color: 66 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_67 << "Color: 67 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_68 << "Color: 68 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_69 << "Color: 69 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_70 << "Color: 70 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_71 << "Color: 71 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_72 << "Color: 72 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_73 << "Color: 73 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_74 << "Color: 74 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_75 << "Color: 75 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_76 << "Color: 76 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_77 << "Color: 77 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_78 << "Color: 78 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_79 << "Color: 79 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_80 << "Color: 80 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_81 << "Color: 81 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_82 << "Color: 82 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_83 << "Color: 83 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_84 << "Color: 84 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_85 << "Color: 85 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_86 << "Color: 86 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_87 << "Color: 87 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_88 << "Color: 88 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_89 << "Color: 89 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_90 << "Color: 90 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_91 << "Color: 91 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_92 << "Color: 92 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_93 << "Color: 93 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_94 << "Color: 94 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_95 << "Color: 95 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_96 << "Color: 96 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_97 << "Color: 97 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_98 << "Color: 98 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_99 << "Color: 99 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_100 << "Color: 100 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_101 << "Color: 101 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_102 << "Color: 102 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_103 << "Color: 103 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_104 << "Color: 104 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_105 << "Color: 105 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_106 << "Color: 106 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_107 << "Color: 107 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_108 << "Color: 108 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_109 << "Color: 109 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_110 << "Color: 110 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_111 << "Color: 111 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_112 << "Color: 112 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_113 << "Color: 113 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_114 << "Color: 114 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_115 << "Color: 115 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_116 << "Color: 116 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_117 << "Color: 117 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_118 << "Color: 118 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_119 << "Color: 119 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_120 << "Color: 120 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_121 << "Color: 121 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_122 << "Color: 122 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_123 << "Color: 123 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_124 << "Color: 124 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_125 << "Color: 125 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_126 << "Color: 126 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_127 << "Color: 127 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_128 << "Color: 128 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_129 << "Color: 129 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_130 << "Color: 130 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_131 << "Color: 131 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_132 << "Color: 132 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_133 << "Color: 133 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_134 << "Color: 134 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_135 << "Color: 135 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_136 << "Color: 136 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_137 << "Color: 137 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_138 << "Color: 138 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_139 << "Color: 139 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_140 << "Color: 140 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_141 << "Color: 141 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_142 << "Color: 142 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_143 << "Color: 143 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_144 << "Color: 144 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_145 << "Color: 145 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_146 << "Color: 146 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_147 << "Color: 147 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_148 << "Color: 148 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_149 << "Color: 149 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_150 << "Color: 150 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_151 << "Color: 151 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_152 << "Color: 152 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_153 << "Color: 153 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_154 << "Color: 154 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_155 << "Color: 155 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_156 << "Color: 156 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_157 << "Color: 157 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_158 << "Color: 158 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_159 << "Color: 159 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_160 << "Color: 160 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_161 << "Color: 161 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_162 << "Color: 162 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_163 << "Color: 163 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_164 << "Color: 164 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_165 << "Color: 165 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_166 << "Color: 166 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_167 << "Color: 167 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_168 << "Color: 168 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_169 << "Color: 169 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_170 << "Color: 170 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_171 << "Color: 171 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_172 << "Color: 172 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_173 << "Color: 173 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_174 << "Color: 174 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_175 << "Color: 175 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_176 << "Color: 176 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_177 << "Color: 177 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_178 << "Color: 178 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_179 << "Color: 179 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_180 << "Color: 180 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_181 << "Color: 181 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_182 << "Color: 182 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_183 << "Color: 183 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_184 << "Color: 184 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_185 << "Color: 185 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_186 << "Color: 186 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_187 << "Color: 187 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_188 << "Color: 188 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_189 << "Color: 189 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_190 << "Color: 190 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_191 << "Color: 191 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_192 << "Color: 192 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_193 << "Color: 193 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_194 << "Color: 194 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_195 << "Color: 195 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_196 << "Color: 196 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_197 << "Color: 197 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_198 << "Color: 198 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_199 << "Color: 199 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_200 << "Color: 200 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_201 << "Color: 201 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_202 << "Color: 202 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_203 << "Color: 203 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_204 << "Color: 204 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_205 << "Color: 205 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_206 << "Color: 206 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_207 << "Color: 207 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_208 << "Color: 208 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_209 << "Color: 209 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_210 << "Color: 210 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_211 << "Color: 211 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_212 << "Color: 212 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_213 << "Color: 213 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_214 << "Color: 214 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_215 << "Color: 215 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_216 << "Color: 216 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_217 << "Color: 217 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_218 << "Color: 218 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_219 << "Color: 219 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_220 << "Color: 220 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_221 << "Color: 221 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_222 << "Color: 222 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_223 << "Color: 223 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_224 << "Color: 224 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_225 << "Color: 225 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_226 << "Color: 226 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_227 << "Color: 227 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_228 << "Color: 228 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_229 << "Color: 229 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_230 << "Color: 230 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_231 << "Color: 231 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_232 << "Color: 232 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_233 << "Color: 233 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_234 << "Color: 234 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_235 << "Color: 235 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_236 << "Color: 236 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_237 << "Color: 237 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_238 << "Color: 238 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_239 << "Color: 239 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_240 << "Color: 240 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_241 << "Color: 241 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_242 << "Color: 242 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_243 << "Color: 243 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_244 << "Color: 244 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_245 << "Color: 245 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_246 << "Color: 246 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_247 << "Color: 247 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_248 << "Color: 248 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_249 << "Color: 249 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_250 << "Color: 250 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_251 << "Color: 251 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_252 << "Color: 252 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_253 << "Color: 253 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_254 << "Color: 254 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_255 << "Color: 255 " << ANSI_COLOR_RESET;
    }

    else if(argv[2] == "--op2" || argv[2] == "-op2"){
        std::cout << ANSI_COLOR_0 << "Color: 0" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_1 << "Color: 1" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_2 << "Color: 2" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_3 << "Color: 3" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_4 << "Color: 4" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_5 << "Color: 5" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_6 << "Color: 6" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_7 << "Color: 7" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_8 << "Color: 8" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_9 << "Color: 9" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_10 << "Color: 10" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_11 << "Color: 11" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_12 << "Color: 12" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_13 << "Color: 13" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_14 << "Color: 14" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_15 << "Color: 15" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_16 << "Color: 16" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_17 << "Color: 17" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_18 << "Color: 18" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_19 << "Color: 19" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_20 << "Color: 20" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_21 << "Color: 21" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_22 << "Color: 22" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_23 << "Color: 23" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_24 << "Color: 24" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_25 << "Color: 25" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_26 << "Color: 26" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_27 << "Color: 27" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_28 << "Color: 28" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_29 << "Color: 29" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_30 << "Color: 30" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_31 << "Color: 31" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_32 << "Color: 32" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_33 << "Color: 33" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_34 << "Color: 34" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_35 << "Color: 35" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_36 << "Color: 36" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_37 << "Color: 37" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_38 << "Color: 38" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_39 << "Color: 39" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_40 << "Color: 40" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_41 << "Color: 41" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_42 << "Color: 42" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_43 << "Color: 43" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_44 << "Color: 44" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_45 << "Color: 45" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_46 << "Color: 46" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_47 << "Color: 47" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_48 << "Color: 48" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_49 << "Color: 49" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_50 << "Color: 50" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_51 << "Color: 51" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_52 << "Color: 52" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_53 << "Color: 53" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_54 << "Color: 54" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_55 << "Color: 55" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_56 << "Color: 56" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_57 << "Color: 57" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_58 << "Color: 58" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_59 << "Color: 59" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_60 << "Color: 60" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_61 << "Color: 61" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_62 << "Color: 62" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_63 << "Color: 63" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_64 << "Color: 64" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_65 << "Color: 65" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_66 << "Color: 66" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_67 << "Color: 67" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_68 << "Color: 68" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_69 << "Color: 69" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_70 << "Color: 70" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_71 << "Color: 71" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_72 << "Color: 72" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_73 << "Color: 73" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_74 << "Color: 74" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_75 << "Color: 75" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_76 << "Color: 76" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_77 << "Color: 77" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_78 << "Color: 78" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_79 << "Color: 79" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_80 << "Color: 80" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_81 << "Color: 81" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_82 << "Color: 82" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_83 << "Color: 83" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_84 << "Color: 84" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_85 << "Color: 85" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_86 << "Color: 86" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_87 << "Color: 87" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_88 << "Color: 88" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_89 << "Color: 89" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_90 << "Color: 90" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_91 << "Color: 91" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_92 << "Color: 92" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_93 << "Color: 93" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_94 << "Color: 94" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_95 << "Color: 95" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_96 << "Color: 96" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_97 << "Color: 97" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_98 << "Color: 98" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_99 << "Color: 99" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_100 << "Color: 100" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_101 << "Color: 101" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_102 << "Color: 102" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_103 << "Color: 103" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_104 << "Color: 104" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_105 << "Color: 105" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_106 << "Color: 106" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_107 << "Color: 107" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_108 << "Color: 108" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_109 << "Color: 109" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_110 << "Color: 110" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_111 << "Color: 111" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_112 << "Color: 112" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_113 << "Color: 113" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_114 << "Color: 114" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_115 << "Color: 115" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_116 << "Color: 116" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_117 << "Color: 117" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_118 << "Color: 118" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_119 << "Color: 119" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_120 << "Color: 120" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_121 << "Color: 121" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_122 << "Color: 122" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_123 << "Color: 123" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_124 << "Color: 124" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_125 << "Color: 125" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_126 << "Color: 126" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_127 << "Color: 127" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_128 << "Color: 128" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_129 << "Color: 129" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_130 << "Color: 130" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_131 << "Color: 131" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_132 << "Color: 132" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_133 << "Color: 133" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_134 << "Color: 134" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_135 << "Color: 135" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_136 << "Color: 136" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_137 << "Color: 137" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_138 << "Color: 138" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_139 << "Color: 139" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_140 << "Color: 140" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_141 << "Color: 141" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_142 << "Color: 142" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_143 << "Color: 143" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_144 << "Color: 144" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_145 << "Color: 145" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_146 << "Color: 146" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_147 << "Color: 147" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_148 << "Color: 148" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_149 << "Color: 149" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_150 << "Color: 150" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_151 << "Color: 151" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_152 << "Color: 152" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_153 << "Color: 153" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_154 << "Color: 154" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_155 << "Color: 155" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_156 << "Color: 156" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_157 << "Color: 157" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_158 << "Color: 158" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_159 << "Color: 159" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_160 << "Color: 160" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_161 << "Color: 161" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_162 << "Color: 162" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_163 << "Color: 163" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_164 << "Color: 164" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_165 << "Color: 165" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_166 << "Color: 166" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_167 << "Color: 167" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_168 << "Color: 168" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_169 << "Color: 169" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_170 << "Color: 170" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_171 << "Color: 171" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_172 << "Color: 172" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_173 << "Color: 173" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_174 << "Color: 174" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_175 << "Color: 175" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_176 << "Color: 176" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_177 << "Color: 177" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_178 << "Color: 178" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_179 << "Color: 179" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_180 << "Color: 180" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_181 << "Color: 181" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_182 << "Color: 182" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_183 << "Color: 183" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_184 << "Color: 184" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_185 << "Color: 185" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_186 << "Color: 186" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_187 << "Color: 187" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_188 << "Color: 188" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_189 << "Color: 189" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_190 << "Color: 190" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_191 << "Color: 191" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_192 << "Color: 192" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_193 << "Color: 193" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_194 << "Color: 194" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_195 << "Color: 195" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_196 << "Color: 196" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_197 << "Color: 197" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_198 << "Color: 198" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_199 << "Color: 199" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_200 << "Color: 200" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_201 << "Color: 201" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_202 << "Color: 202" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_203 << "Color: 203" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_204 << "Color: 204" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_205 << "Color: 205" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_206 << "Color: 206" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_207 << "Color: 207" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_208 << "Color: 208" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_209 << "Color: 209" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_210 << "Color: 210" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_211 << "Color: 211" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_212 << "Color: 212" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_213 << "Color: 213" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_214 << "Color: 214" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_215 << "Color: 215" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_216 << "Color: 216" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_217 << "Color: 217" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_218 << "Color: 218" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_219 << "Color: 219" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_220 << "Color: 220" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_221 << "Color: 221" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_222 << "Color: 222" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_223 << "Color: 223" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_224 << "Color: 224" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_225 << "Color: 225" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_226 << "Color: 226" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_227 << "Color: 227" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_228 << "Color: 228" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_229 << "Color: 229" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_230 << "Color: 230" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_231 << "Color: 231" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_232 << "Color: 232" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_233 << "Color: 233" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_234 << "Color: 234" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_235 << "Color: 235" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_236 << "Color: 236" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_237 << "Color: 237" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_238 << "Color: 238" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_239 << "Color: 239" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_240 << "Color: 240" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_241 << "Color: 241" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_242 << "Color: 242" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_243 << "Color: 243" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_244 << "Color: 244" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_245 << "Color: 245" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_246 << "Color: 246" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_247 << "Color: 247" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_248 << "Color: 248" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_249 << "Color: 249" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_250 << "Color: 250" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_251 << "Color: 251" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_252 << "Color: 252" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_253 << "Color: 253" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_254 << "Color: 254" << ANSI_COLOR_RESET << std::endl;
        std::cout << ANSI_COLOR_255 << "Color: 255" << ANSI_COLOR_RESET << std::endl;

    }

    else if(argv[2] == "-op3" || argv[2] == "--op3"){
        
        std::cout << ANSI_COLOR_0 << " Color: 0 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_1 << " Color: 1 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_2 << " Color: 2 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_3 << " Color: 3 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_4 << " Color: 4 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_5 << " Color: 5 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_6 << " Color: 6 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_7 << " Color: 7 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_8 << " Color: 8 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_9 << " Color: 9 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_10 << " Color: 10 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_11 << " Color: 11 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_12 << " Color: 12 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_13 << " Color: 13 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_14 << " Color: 14 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_15 << " Color: 15 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_16 << " Color: 16 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_17 << " Color: 17 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_18 << " Color: 18 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_19 << " Color: 19 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_20 << " Color: 20 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_21 << " Color: 21 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_22 << " Color: 22 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_23 << " Color: 23 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_24 << " Color: 24 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_25 << " Color: 25 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_26 << " Color: 26 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_27 << " Color: 27 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_28 << " Color: 28 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_29 << " Color: 29 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_30 << " Color: 30 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_31 << " Color: 31 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_32 << " Color: 32 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_33 << " Color: 33 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_34 << " Color: 34 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_35 << " Color: 35 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_36 << " Color: 36 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_37 << " Color: 37 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_38 << " Color: 38 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_39 << " Color: 39 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_40 << " Color: 40 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_41 << " Color: 41 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_42 << " Color: 42 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_43 << " Color: 43 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_44 << " Color: 44 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_45 << " Color: 45 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_46 << " Color: 46 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_47 << " Color: 47 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_48 << " Color: 48 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_49 << " Color: 49 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_50 << " Color: 50 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_51 << " Color: 51 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_52 << " Color: 52 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_53 << " Color: 53 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_54 << " Color: 54 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_55 << " Color: 55 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_56 << " Color: 56 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_57 << " Color: 57 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_58 << " Color: 58 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_59 << " Color: 59 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_60 << " Color: 60 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_61 << " Color: 61 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_62 << " Color: 62 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_63 << " Color: 63 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_64 << " Color: 64 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_65 << " Color: 65 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_66 << " Color: 66 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_67 << " Color: 67 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_68 << " Color: 68 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_69 << " Color: 69 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_70 << " Color: 70 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_71 << " Color: 71 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_72 << " Color: 72 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_73 << " Color: 73 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_74 << " Color: 74 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_75 << " Color: 75 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_76 << " Color: 76 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_77 << " Color: 77 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_78 << " Color: 78 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_79 << " Color: 79 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_80 << " Color: 80 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_81 << " Color: 81 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_82 << " Color: 82 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_83 << " Color: 83 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_84 << " Color: 84 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_85 << " Color: 85 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_86 << " Color: 86 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_87 << " Color: 87 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_88 << " Color: 88 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_89 << " Color: 89 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_90 << " Color: 90 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_91 << " Color: 91 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_92 << " Color: 92 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_93 << " Color: 93 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_94 << " Color: 94 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_95 << " Color: 95 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_96 << " Color: 96 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_97 << " Color: 97 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_98 << " Color: 98 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_99 << " Color: 99 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_100 << " Color: 100 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_101 << " Color: 101 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_102 << " Color: 102 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_103 << " Color: 103 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_104 << " Color: 104 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_105 << " Color: 105 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_106 << " Color: 106 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_107 << " Color: 107 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_108 << " Color: 108 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_109 << " Color: 109 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_110 << " Color: 110 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_111 << " Color: 111 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_112 << " Color: 112 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_113 << " Color: 113 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_114 << " Color: 114 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_115 << " Color: 115 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_116 << " Color: 116 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_117 << " Color: 117 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_118 << " Color: 118 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_119 << " Color: 119 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_120 << " Color: 120 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_121 << " Color: 121 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_122 << " Color: 122 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_123 << " Color: 123 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_124 << " Color: 124 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_125 << " Color: 125 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_126 << " Color: 126 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_127 << " Color: 127 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_128 << " Color: 128 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_129 << " Color: 129 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_130 << " Color: 130 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_131 << " Color: 131 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_132 << " Color: 132 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_133 << " Color: 133 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_134 << " Color: 134 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_135 << " Color: 135 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_136 << " Color: 136 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_137 << " Color: 137 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_138 << " Color: 138 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_139 << " Color: 139 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_140 << " Color: 140 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_141 << " Color: 141 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_142 << " Color: 142 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_143 << " Color: 143 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_144 << " Color: 144 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_145 << " Color: 145 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_146 << " Color: 146 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_147 << " Color: 147 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_148 << " Color: 148 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_149 << " Color: 149 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_150 << " Color: 150 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_151 << " Color: 151 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_152 << " Color: 152 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_153 << " Color: 153 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_154 << " Color: 154 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_155 << " Color: 155 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_156 << " Color: 156 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_157 << " Color: 157 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_158 << " Color: 158 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_159 << " Color: 159 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_160 << " Color: 160 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_161 << " Color: 161 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_162 << " Color: 162 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_163 << " Color: 163 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_164 << " Color: 164 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_165 << " Color: 165 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_166 << " Color: 166 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_167 << " Color: 167 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_168 << " Color: 168 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_169 << " Color: 169 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_170 << " Color: 170 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_171 << " Color: 171 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_172 << " Color: 172 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_173 << " Color: 173 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_174 << " Color: 174 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_175 << " Color: 175 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_176 << " Color: 176 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_177 << " Color: 177 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_178 << " Color: 178 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_179 << " Color: 179 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_180 << " Color: 180 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_181 << " Color: 181 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_182 << " Color: 182 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_183 << " Color: 183 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_184 << " Color: 184 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_185 << " Color: 185 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_186 << " Color: 186 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_187 << " Color: 187 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_188 << " Color: 188 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_189 << " Color: 189 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_190 << " Color: 190 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_191 << " Color: 191 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_192 << " Color: 192 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_193 << " Color: 193 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_194 << " Color: 194 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_195 << " Color: 195 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_196 << " Color: 196 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_197 << " Color: 197 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_198 << " Color: 198 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_199 << " Color: 199 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_200 << " Color: 200 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_201 << " Color: 201 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_202 << " Color: 202 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_203 << " Color: 203 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_204 << " Color: 204 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_205 << " Color: 205 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_206 << " Color: 206 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_207 << " Color: 207 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_208 << " Color: 208 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_209 << " Color: 209 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_210 << " Color: 210 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_211 << " Color: 211 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_212 << " Color: 212 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_213 << " Color: 213 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_214 << " Color: 214 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_215 << " Color: 215 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_216 << " Color: 216 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_217 << " Color: 217 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_218 << " Color: 218 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_219 << " Color: 219 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_220 << " Color: 220 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_221 << " Color: 221 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_222 << " Color: 222 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_223 << " Color: 223 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_224 << " Color: 224 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_225 << " Color: 225 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_226 << " Color: 226 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_227 << " Color: 227 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_228 << " Color: 228 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_229 << " Color: 229 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_230 << " Color: 230 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_231 << " Color: 231 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_232 << " Color: 232 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_233 << " Color: 233 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_234 << " Color: 234 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_235 << " Color: 235 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_236 << " Color: 236 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_237 << " Color: 237 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_238 << " Color: 238 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_239 << " Color: 239 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_240 << " Color: 240 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_241 << " Color: 241 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_242 << " Color: 242 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_243 << " Color: 243 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_244 << " Color: 244 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_245 << " Color: 245 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_246 << " Color: 246 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_247 << " Color: 247 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_248 << " Color: 248 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_249 << " Color: 249 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_250 << " Color: 250 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_251 << " Color: 251 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_252 << " Color: 252 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_253 << " Color: 253 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_254 << " Color: 254 " << ANSI_COLOR_RESET;
        std::cout << ANSI_COLOR_255 << " Color: 255 " << ANSI_COLOR_RESET;
    }
}